# Generated by Django 5.1.3 on 2026-06-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mensagem_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensagem',
            new_name='Message',
        ),
    ]
